# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Zhouer's Blog"
weight = 1

[zh-cn]
languageName = "中文"
languagedirection = "ltr"
title = "淍儿的博客"
weight = 1
