# Configure main menu and social menu

# content目录下的及各子目录下的_index.md里的配置可以覆盖main的配置，直接配置main高亮？
# [[main]]
# identifier = "home"
# name = "主页"
# url = "/"
# [main.params]
# icon = "home"
# newtab = false

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/zhouer1"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/zhur370065"

[social.params]
icon = "brand-x"

[[social]]
identifier = "email"
name = "email"
url = "mailto:zhouer1mail@qq.com"

[social.params]
icon = "mail"
